In [42]:
import quandl
import pandas as pd
import numpy as np
symbol = 'WIKI/GOOG'
df1 = quandl.get(symbol,start_date='2011-01-01',end_date='2016-12-31')
df2 = quandl.get('WIKI/AAPL',start_date='2011-01-01',end_date='2016-12-31')
df3 = quandl.get('WIKI/FB',start_date='2011-01-01',end_date='2016-12-31')
df1 = pd.DataFrame(df1,columns=['Close'])
df2 = pd.DataFrame(df2,columns=['Close'])
df3 = pd.DataFrame(df3,columns=['Close'])
df1.columns=['GOOG']
df2.columns=['AAPL']
df3.columns=['FB']
exl = pd.concat([df1,df2,df3],axis=1)
exl

              GOOG    AAPL      FB
Date
2011-01-03     NaN  329.57     NaN
2011-01-04     NaN  331.29     NaN
2011-01-05     NaN  334.00     NaN
2011-01-06     NaN  333.73     NaN
2011-01-07     NaN  336.12     NaN
...            ...     ...     ...
2016-12-23  789.91  116.52  117.27
2016-12-27  791.55  117.26  118.01
2016-12-28  785.05  116.76  116.92
2016-12-29  782.79  116.73  116.35
2016-12-30  771.82  115.82  115.05

[1510 rows x 3 columns]

In [44]:
type(exl)
exl = exl.fillna(exl.mean(axis=0))
exl

                  GOOG    AAPL          FB
Date
2011-01-03  639.957563  329.57   70.470235
2011-01-04  639.957563  331.29   70.470235
2011-01-05  639.957563  334.00   70.470235
2011-01-06  639.957563  333.73   70.470235
2011-01-07  639.957563  336.12   70.470235
...                ...     ...         ...
2016-12-23  789.910000  116.52  117.270000
2016-12-27  791.550000  117.26  118.010000
2016-12-28  785.050000  116.76  116.920000
2016-12-29  782.790000  116.73  116.350000
2016-12-30  771.820000  115.82  115.050000

[1510 rows x 3 columns]

In [55]:
import matplotlib.pylab as plt
import statsmodels.api as sm
exl['intercept'] = 1

In [58]:
X = exl[['intercept', 'AAPL', 'FB']]
y = exl['GOOG']

# 拟合多元线性回归模型
model = sm.OLS(y, X).fit()

# 获取回归结果
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   GOOG   R-squared:                       0.314
Model:                            OLS   Adj. R-squared:                  0.313
Method:                 Least Squares   F-statistic:                     344.1
Date:                Wed, 27 Mar 2024   Prob (F-statistic):          7.86e-124
Time:                        16:06:56   Log-Likelihood:                -8181.7
No. Observations:                1510   AIC:                         1.637e+04
Df Residuals:                    1507   BIC:                         1.639e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept    443.1928      8.664     51.151      0.000     426.197     460.188
AAPL           0.1877      0.011     16.359      0.000       0.165       0.210
FB             1.9352      0.076     25.543      0.000       1.787       2.084
==============================================================================
Omnibus:                       62.225   Durbin-Watson:                   0.016
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               65.111
Skew:                          -0.483   Prob(JB):                     7.27e-15
Kurtosis:                       2.680   Cond. No.                     2.35e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.35e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [59]:
df1 = quandl.get(symbol,start_date='2017-01-01',end_date='2018-12-31')
df2 = quandl.get('WIKI/AAPL',start_date='2017-01-01',end_date='2018-12-31')
df3 = quandl.get('WIKI/FB',start_date='2017-01-01',end_date='2018-12-31')
df1 = pd.DataFrame(df1,columns=['Close'])
df2 = pd.DataFrame(df2,columns=['Close'])
df3 = pd.DataFrame(df3,columns=['Close'])
df1.columns=['GOOG']
df2.columns=['AAPL']
df3.columns=['FB']
new_exl = pd.concat([df1,df2,df3],axis=1)
new_exl

               GOOG     AAPL      FB
Date
2017-01-03   786.14  116.150  116.86
2017-01-04   786.90  116.020  118.69
2017-01-05   794.02  116.610  120.67
2017-01-06   806.15  117.910  123.41
2017-01-09   806.65  118.990  124.90
...             ...      ...     ...
2018-03-21  1090.88  171.270  169.39
2018-03-22  1049.08  168.845  164.89
2018-03-23  1021.57  164.940  159.39
2018-03-26  1053.21  172.770  160.06
2018-03-27  1005.10  168.340  152.19

[309 rows x 3 columns]

In [63]:
new_exl = pd.DataFrame(new_exl)
new_exl['intercept'] = 1
new_exl

               GOOG     AAPL      FB  intercept
Date
2017-01-03   786.14  116.150  116.86          1
2017-01-04   786.90  116.020  118.69          1
2017-01-05   794.02  116.610  120.67          1
2017-01-06   806.15  117.910  123.41          1
2017-01-09   806.65  118.990  124.90          1
...             ...      ...     ...        ...
2018-03-21  1090.88  171.270  169.39          1
2018-03-22  1049.08  168.845  164.89          1
2018-03-23  1021.57  164.940  159.39          1
2018-03-26  1053.21  172.770  160.06          1
2018-03-27  1005.10  168.340  152.19          1

[309 rows x 4 columns]

In [64]:
predictions = model.predict(new_exl)

print(predictions)

ValueError: shapes (309,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)