# Series对象
pandas库的一种数据结构类似于一维数组。由一组数据和这组数据有关的标签组成。
series可以储存int，floot，str和python对象等数据类型

In [1]:
import pandas as pd

In [2]:
data = ['李光地','张红云','王鹏']
s = pd.Series(data=data)
print(s)

0    李光地
1    张红云
2     王鹏
dtype: object

In [3]:
type(s)

pandas.core.series.Series

In [4]:
data = [11,22,33]
index = ['张三','李四','王五']
a = pd.Series(data,index)
print(a)

张三    11
李四    22
王五    33
dtype: int64

Series索引
位置索引 范围[0,n-1]
标签索引 [索引名称],获取多个标签索引值使用[[标签1],[标签2]，...]
切片索引 [start:stop:step]
获取Series索引和值 获取索引 s.index 获取值 s.values

In [5]:
print(s[0])

李光地

In [6]:
print(a['张三'])

11

In [7]:
print(a[['张三','李四','王五']])

张三    11
李四    22
王五    33
dtype: int64

In [8]:
print(s[0:2])#位置切片含头不含尾

0    李光地
1    张红云
dtype: object

In [9]:
print(a['张三':'王五']) #标签索引含头含尾

张三    11
李四    22
王五    33
dtype: int64

In [10]:
a.index[0]
a.values[0]

11

In [11]:
s.values

array(['李光地', '张红云', '王鹏'], dtype=object)

# DataFrame对象
DataFrame 是pandas的一种数据结构，类似于二维表，由行和列组成

In [12]:
#b = pd.DataFrame(data,index,columns,dtype)

In [13]:
#列表方式
data = [['小太阳',320.9,100],['鼠标',150.3,50],['小刀',1.5,200]]
print(data)

[['小太阳', 320.9, 100], ['鼠标', 150.3, 50], ['小刀', 1.5, 200]]

In [14]:
columns = ['名称','单价','数量']
df = pd.DataFrame(data=data,columns=columns)
df

    名称     单价   数量
0  小太阳  320.9  100
1   鼠标  150.3   50
2   小刀    1.5  200

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
#字典方式创建DataFrame
data ={
    '名称':['小太阳','鼠标','小刀'],
    '单价':[320.9,150.3,1.5],
    '数量':[100,50,200]
}
df = pd.DataFrame(data=data)
df

    名称     单价   数量
0  小太阳  320.9  100
1   鼠标  150.3   50
2   小刀    1.5  200

In [17]:
#字典列表必须长度一致
data ={
    '名称':['小太阳','鼠标','小刀','大刀'],
    '单价':[320.9,150.3,1.5],
    '数量':[100,50,200]
}
df = pd.DataFrame(data=data)
df

ValueError: All arrays must be of the same length

In [ ]:
#字符串会为每行添加
data ={
    '名称':['小太阳','鼠标','小刀'],
    '单价':[320.9,150.3,1.5],
    '数量':[100,50,200],
    '公司': '东门超市'
}
df = pd.DataFrame(data=data)
df

DataFrame的重要属性
1.values 是查看所有元素的值
2.dtypes 查看所有元素的类型
3.columns 查看所有列名，重命名列名
4.index 查看所有行名，重命名行名
5.T 行列数据转换
6.head 查看前N条数据 默认为5条
7.tail 查看后N条数据 默认为5条
8.shape 查看行数和列数shape[0]表示行shape[1]表示列
9 info 查看索引，数据类型和内存信息

In [18]:
df.values

array([['小太阳', 320.9, 100],
       ['鼠标', 150.3, 50],
       ['小刀', 1.5, 200]], dtype=object)

In [19]:
df.dtypes

名称     object
单价    float64
数量      int64
dtype: object

In [20]:
df.columns

Index(['名称', '单价', '数量'], dtype='object')

In [21]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [22]:
df.T

        0      1    2
名称    小太阳     鼠标   小刀
单价  320.9  150.3  1.5
数量    100     50  200

In [23]:
df.head(1)

    名称     单价   数量
0  小太阳  320.9  100

In [24]:
df.tail(1)

   名称   单价   数量
2  小刀  1.5  200

In [25]:
df.shape[0]

3

In [26]:
df.info

<bound method DataFrame.info of     名称     单价   数量
0  小太阳  320.9  100
1   鼠标  150.3   50
2   小刀    1.5  200>

DataFrame的重要函数
1.describe() 查看每列的统计汇总信息，DataFrame类型
2.count（） 返回每列非空值的个数
3.sum() 返回每列的和，无法计算返回空值
4.max() 返回每列的最大值
5.min() 返回每列的最小值

In [27]:
df.describe()

               单价          数量
count    3.000000    3.000000
mean   157.566667  116.666667
std    159.823945   76.376262
min      1.500000   50.000000
25%     75.900000   75.000000
50%    150.300000  100.000000
75%    235.600000  150.000000
max    320.900000  200.000000

In [28]:
df.count()

名称    3
单价    3
数量    3
dtype: int64

In [29]:
df.sum()

名称    小太阳鼠标小刀
单价      472.7
数量        350
dtype: object

In [30]:
df.max()

名称       鼠标
单价    320.9
数量      200
dtype: object

In [31]:
df.min()

名称     小刀
单价    1.5
数量     50
dtype: object

# 导入外部数据

In [37]:
#导入.xls或者.xlsx文件
#pd.read_excel(io,sheet_name,header) io为文件路径 sheet_name表示工作表sheet_name=0 第一页数据，sheet_name=1第二页数据，sheet_name='Sheet1'读取名称为Sheet1页，sheet_name=[0,1,'Sheet3']表示读取第一个，第二个和Sheet3的页，sheet_name=None读取所有的工作表
#header默认为0，取第一行的值为列名，数据为除去列名外的数据，如果数据不含列名则设置heardr=None

In [38]:
 a = pd.read_excel('1.xlsx',sheet_name=0,header=0)
a
a.to_csv('a.csv')

In [39]:
#导入一列数据
pd.read_excel('1.xlsx',sheet_name=0,usecols=[3])

        SPX
0    46.760
1    46.325
2    45.650
3    46.230
4    47.590
..      ...
166  43.520
167  41.820
168  43.360
169  43.500
170  42.610

[171 rows x 1 columns]

In [40]:
#导入多列数据
pd.set_option('display.unicode.east_asian_width',True)
pd.read_excel('1.xlsx',sheet_name=0,usecols=['Date','AAPL'])

          Date    AAPL
0   2015-01-02  109.33
1   2015-01-05  106.25
2   2015-01-06  106.26
3   2015-01-07  107.75
4   2015-01-08  111.89
..         ...     ...
166 2015-08-31  112.76
167 2015-09-01  107.72
168 2015-09-02  112.34
169 2015-09-03  110.37
170 2015-09-04  109.27

[171 rows x 2 columns]

In [32]:
#导入csv文件/txt文件
#pd.read_csv(filepath_or_buffer,sep=',',header,encoding=None)
#filepath_or_buffer可以是字符串，文件路径也可以是URL链接 sep字符串，分隔符 encoding 字符串 默认为None 文件编码格式

In [41]:
df= pd.read_csv('a.csv',sep=',',encoding=None)
df.head()

   Unnamed: 0        Date    GOOG    AAPL     SPX
0           0  2015-01-02  109.33  109.33  46.760
1           1  2015-01-05  106.25  106.25  46.325
2           2  2015-01-06  106.26  106.26  45.650
3           3  2015-01-07  107.75  107.75  46.230
4           4  2015-01-08  111.89  111.89  47.590

In [42]:
#导入HTML网页
url = 'http://www.espn.com/nba/salaries'
#获得数据
tables = pd.read_html(url,header=0)
df =pd.DataFrame(data=tables[0])
df.to_csv('nba.csv',index=False)

# 数据抽取
DataFrame对象中的loc属性和iloc属性
loc属性 ：以列名和行名为参数，当只有一个参数时候，默认是行名，即抽取整行的数据，包括所有列。
iloc属性：以行和列位置为索引(即0，1，2)作为参数，0表示第一行，1表示第二行。当只有一个参数时，默认行索引，即抽取整行数据包括所有列。

In [43]:
data=[[45,65,100],[56,45,50],[67,67,67]]
index = ['张三','李四','王五']
columns = ['语文','数学','英语']
df = pd.DataFrame(data,index,columns)
df

      语文  数学  英语
张三    45    65   100
李四    56    45    50
王五    67    67    67

In [44]:
#提去一行 行索引名称
df.loc['张三']

语文     45
数学     65
英语    100
Name: 张三, dtype: int64

In [45]:
#提去一行 行索引编号
df.iloc[0]

语文     45
数学     65
英语    100
Name: 张三, dtype: int64

In [46]:
#提取多行数据
df.loc[['张三','王五']]

      语文  数学  英语
张三    45    65   100
王五    67    67    67

In [47]:
#提取多行数据
df.iloc[[0,2]]

      语文  数学  英语
张三    45    65   100
王五    67    67    67

In [48]:
#提取连续的多行数据
df.loc['张三':'王五']

      语文  数学  英语
张三    45    65   100
李四    56    45    50
王五    67    67    67

In [49]:
#提取连续的多行数据
df.iloc[0:3]

      语文  数学  英语
张三    45    65   100
李四    56    45    50
王五    67    67    67

提取列数据

In [50]:
#直接提取列数据
df[['语文','数学']]

      语文  数学
张三    45    65
李四    56    45
王五    67    67

In [51]:
#loc提取列数据
df.loc[:,['语文','英语']]

      语文  英语
张三    45   100
李四    56    50
王五    67    67

In [52]:
df.loc[:,'语文']

张三    45
李四    56
王五    67
Name: 语文, dtype: int64

In [53]:
df.loc[:,'语文':'英语']

      语文  数学  英语
张三    45    65   100
李四    56    45    50
王五    67    67    67

In [54]:
#iloc提取数据
df.iloc[:,0]

张三    45
李四    56
王五    67
Name: 语文, dtype: int64

In [55]:
df.iloc[:,[0,2]]

      语文  英语
张三    45   100
李四    56    50
王五    67    67

In [56]:
df.iloc[:,0:3]

      语文  数学  英语
张三    45    65   100
李四    56    45    50
王五    67    67    67

In [57]:
#提取区域数据
df.loc[['张三','王五'],['语文','数学']]

      语文  数学
张三    45    65
王五    67    67

In [58]:
df.iloc[:,[1,2]]

      数学  英语
张三    65   100
李四    45    50
王五    67    67

In [59]:
df.iloc[:,0]

张三    45
李四    56
王五    67
Name: 语文, dtype: int64

In [52]:
#按指定条件提取数据
df.loc[df['语文']>=60]

      语文  数学  英语
王五    67    67    67

In [53]:
df.loc[(df['语文']>=60) & (df['数学']>=60)]

      语文  数学  英语
王五    67    67    67

# 数据的增加,修改和删除
数据的增加 按行增加，按列增加，增加多行
修改数据  作改列标题，修改行标题，修改数据
删除数据
参数说明 labels表示行标签或者列标签 axis:axis=0表示按行删除 axis=1表示按列删除  index 删除行 默认为None columns 删除列 默认None inplace 对原数组作出修改并返回新数组。 默认为False ，如果为True那么原来的数组会消失。

In [60]:
#数据增加-按列增加
#直接赋值
df['政治']=[90,89,100]
df

      语文  数学  英语  政治
张三    45    65   100    90
李四    56    45    50    89
王五    67    67    67   100

In [61]:
#使用loc
df.loc[:,'化学']=[100,30,98]
df

      语文  数学  英语  政治  化学
张三    45    65   100    90   100
李四    56    45    50    89    30
王五    67    67    67   100    98

In [62]:
#在指定的索引上进行插入一列
lst = [100,99,90]
df.insert(1,'历史',lst)
df

      语文  历史  数学  英语  政治  化学
张三    45   100    65   100    90   100
李四    56    99    45    50    89    30
王五    67    90    67    67   100    98

In [63]:
#按行增加 loc
df.loc['老六',:]=[60,60,60,60,60,60]
df

      语文   历史  数学   英语   政治   化学
张三  45.0  100.0  65.0  100.0   90.0  100.0
李四  56.0   99.0  45.0   50.0   89.0   30.0
王五  67.0   90.0  67.0   67.0  100.0   98.0
老六  60.0   60.0  60.0   60.0   60.0   60.0

In [64]:
#新建DataFrame的方式
new_data=pd.DataFrame(
data={
    '数学':[88,77],
    '语文':[90,89],
    '英语':[70,77]
},index=['小七','王一一'])
df=df._append(new_data)
df

        语文   历史  数学   英语   政治   化学
张三    45.0  100.0  65.0  100.0   90.0  100.0
李四    56.0   99.0  45.0   50.0   89.0   30.0
王五    67.0   90.0  67.0   67.0  100.0   98.0
老六    60.0   60.0  60.0   60.0   60.0   60.0
小七    90.0    NaN  88.0   70.0    NaN    NaN
王一一  89.0    NaN  77.0   77.0    NaN    NaN

In [65]:
#修改列标题
#直接使用columns
df.columns=['数学上','历史上','语文上','英语上','政治上','化学上']
df

        数学上  历史上  语文上  英语上  政治上  化学上
张三      45.0   100.0    65.0   100.0    90.0   100.0
李四      56.0    99.0    45.0    50.0    89.0    30.0
王五      67.0    90.0    67.0    67.0   100.0    98.0
老六      60.0    60.0    60.0    60.0    60.0    60.0
小七      90.0     NaN    88.0    70.0     NaN     NaN
王一一    89.0     NaN    77.0    77.0     NaN     NaN

In [66]:
#rename inplace是否直接修改dataframe属性
df.rename(columns={'数学上':'数学下','历史上':'历史下','语文上':'语文下','英语上':'英语下','政治上':'政治下','化学上':'化学下'},inplace=True)
df

        数学下  历史下  语文下  英语下  政治下  化学下
张三      45.0   100.0    65.0   100.0    90.0   100.0
李四      56.0    99.0    45.0    50.0    89.0    30.0
王五      67.0    90.0    67.0    67.0   100.0    98.0
老六      60.0    60.0    60.0    60.0    60.0    60.0
小七      90.0     NaN    88.0    70.0     NaN     NaN
王一一    89.0     NaN    77.0    77.0     NaN     NaN

In [67]:
#修改行标签
#直接赋值
df.index=list('123456')
df

   数学下  历史下  语文下  英语下  政治下  化学下
1    45.0   100.0    65.0   100.0    90.0   100.0
2    56.0    99.0    45.0    50.0    89.0    30.0
3    67.0    90.0    67.0    67.0   100.0    98.0
4    60.0    60.0    60.0    60.0    60.0    60.0
5    90.0     NaN    88.0    70.0     NaN     NaN
6    89.0     NaN    77.0    77.0     NaN     NaN

In [62]:
#rename 
df.rename({'1':'一','2':'二','3':'三','4':'四','5':'五','6':'六'},inplace=True)
df

    数学下  历史下  语文下  英语下  政治下  化学下
一    45.0   100.0    65.0   100.0    90.0   100.0
二    56.0    99.0    45.0    50.0    89.0    30.0
三    67.0    90.0    67.0    67.0   100.0    98.0
四    60.0    60.0    60.0    60.0    60.0    60.0
五    90.0     NaN    88.0    70.0     NaN     NaN
六    89.0     NaN    77.0    77.0     NaN     NaN

In [63]:
df.index=[1,2,3,4,5,6]
df

   数学下  历史下  语文下  英语下  政治下  化学下
1    45.0   100.0    65.0   100.0    90.0   100.0
2    56.0    99.0    45.0    50.0    89.0    30.0
3    67.0    90.0    67.0    67.0   100.0    98.0
4    60.0    60.0    60.0    60.0    60.0    60.0
5    90.0     NaN    88.0    70.0     NaN     NaN
6    89.0     NaN    77.0    77.0     NaN     NaN

In [68]:
#修改一整行
#loc
df.loc['张三']=[100,100,120]
df

ValueError: cannot set a row with mismatched columns

In [69]:
#iloc
df.iloc[0,:]=[110,100,100]
df

ValueError: Must have equal len keys and value when setting with an iterable

In [70]:
#修改一列 loc
df.loc[:,'数学']=[100,100,100]
df

ValueError: Length of values (3) does not match length of index (6)

In [71]:
#iloc
df.iloc[:,1]=[80,80,80]
df

ValueError: Must have equal len keys and value when setting with an iterable

In [ ]:
#修改某一个数据
df.loc['李四','语文']=100
df

In [ ]:
df.iloc[1,0]=80
df

In [ ]:
#数据删除
#删除列
df.drop(['数学'],axis=1,inplace=True)
df.drop(columns='数学',inplace=True)
df.drop(labels='数学',axis=1,inplace=True)
df

In [ ]:
#删除行
df.drop(['张三'],axis=0,inplace=True)
df.drop(index='张三',inplace=True)
df.drop(labels='张三',axis=0,inplace=True)
df

In [ ]:
#有条件的删除
df.drop(df[df['英语']<=60].index,inplace=True)
df

# 数据清洗
查看缺少值 使用DataFrame对象的info()方法
判断数据是否存在缺少值 使用Dataframe的isnull()方法或者notnull()方法
缺失值处理方法 不处理 删除 填充或者替换 插值
重复值处理 删除

In [72]:
data = pd.read_excel('1.xlsx',header=0)
data

          Date    GOOG    AAPL     SPX
0   2015-01-02  109.33  109.33  46.760
1   2015-01-05  106.25  106.25  46.325
2   2015-01-06  106.26  106.26  45.650
3   2015-01-07  107.75  107.75  46.230
4   2015-01-08  111.89  111.89  47.590
..         ...     ...     ...     ...
166 2015-08-31  112.76  112.76  43.520
167 2015-09-01  107.72  107.72  41.820
168 2015-09-02  112.34  112.34  43.360
169 2015-09-03  110.37  110.37  43.500
170 2015-09-04  109.27  109.27  42.610

[171 rows x 4 columns]

In [73]:
data.iloc[0,3]=None
data.iloc[1,2]=None
data

          Date    GOOG    AAPL     SPX
0   2015-01-02  109.33  109.33     NaN
1   2015-01-05  106.25     NaN  46.325
2   2015-01-06  106.26  106.26  45.650
3   2015-01-07  107.75  107.75  46.230
4   2015-01-08  111.89  111.89  47.590
..         ...     ...     ...     ...
166 2015-08-31  112.76  112.76  43.520
167 2015-09-01  107.72  107.72  41.820
168 2015-09-02  112.34  112.34  43.360
169 2015-09-03  110.37  110.37  43.500
170 2015-09-04  109.27  109.27  42.610

[171 rows x 4 columns]

In [74]:
#查看是否有缺失值
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    171 non-null    datetime64[ns]
 1   GOOG    171 non-null    float64
 2   AAPL    170 non-null    float64
 3   SPX     170 non-null    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 5.5 KB

In [75]:
#判断是否有缺失值
data.isnull()

      Date   GOOG   AAPL    SPX
0    False  False  False   True
1    False  False   True  False
2    False  False  False  False
3    False  False  False  False
4    False  False  False  False
..     ...    ...    ...    ...
166  False  False  False  False
167  False  False  False  False
168  False  False  False  False
169  False  False  False  False
170  False  False  False  False

[171 rows x 4 columns]

In [76]:
data.notnull()

     Date  GOOG   AAPL    SPX
0    True  True   True  False
1    True  True  False   True
2    True  True   True   True
3    True  True   True   True
4    True  True   True   True
..    ...   ...    ...    ...
166  True  True   True   True
167  True  True   True   True
168  True  True   True   True
169  True  True   True   True
170  True  True   True   True

[171 rows x 4 columns]

In [77]:
#缺失值的处理
#删除
data1 = data.dropna()
data1

          Date    GOOG    AAPL    SPX
2   2015-01-06  106.26  106.26  45.65
3   2015-01-07  107.75  107.75  46.23
4   2015-01-08  111.89  111.89  47.59
5   2015-01-09  112.01  112.01  47.19
6   2015-01-12  109.25  109.25  46.60
..         ...     ...     ...    ...
166 2015-08-31  112.76  112.76  43.52
167 2015-09-01  107.72  107.72  41.82
168 2015-09-02  112.34  112.34  43.36
169 2015-09-03  110.37  110.37  43.50
170 2015-09-04  109.27  109.27  42.61

[169 rows x 4 columns]

In [78]:
#提取某一行不为nan的
w=data[data['AAPL'].notnull()]

In [79]:
w

          Date    GOOG    AAPL    SPX
0   2015-01-02  109.33  109.33    NaN
2   2015-01-06  106.26  106.26  45.65
3   2015-01-07  107.75  107.75  46.23
4   2015-01-08  111.89  111.89  47.59
5   2015-01-09  112.01  112.01  47.19
..         ...     ...     ...    ...
166 2015-08-31  112.76  112.76  43.52
167 2015-09-01  107.72  107.72  41.82
168 2015-09-02  112.34  112.34  43.36
169 2015-09-03  110.37  110.37  43.50
170 2015-09-04  109.27  109.27  42.61

[170 rows x 4 columns]

In [80]:
#缺失值的填充
a=data['AAPL'].mean()
a
data['AAPL']=data['AAPL'].fillna(data['AAPL'].mean())
data

          Date    GOOG        AAPL     SPX
0   2015-01-02  109.33  109.330000     NaN
1   2015-01-05  106.25  122.938765  46.325
2   2015-01-06  106.26  106.260000  45.650
3   2015-01-07  107.75  107.750000  46.230
4   2015-01-08  111.89  111.890000  47.590
..         ...     ...         ...     ...
166 2015-08-31  112.76  112.760000  43.520
167 2015-09-01  107.72  107.720000  41.820
168 2015-09-02  112.34  112.340000  43.360
169 2015-09-03  110.37  110.370000  43.500
170 2015-09-04  109.27  109.270000  42.610

[171 rows x 4 columns]

In [82]:
#判断有无重复值
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
166    False
167    False
168    False
169    False
170    False
Length: 171, dtype: bool

In [83]:
#删除重复值
data.drop_duplicates()

          Date    GOOG        AAPL     SPX
0   2015-01-02  109.33  109.330000     NaN
1   2015-01-05  106.25  122.938765  46.325
2   2015-01-06  106.26  106.260000  45.650
3   2015-01-07  107.75  107.750000  46.230
4   2015-01-08  111.89  111.890000  47.590
..         ...     ...         ...     ...
166 2015-08-31  112.76  112.760000  43.520
167 2015-09-01  107.72  107.720000  41.820
168 2015-09-02  112.34  112.340000  43.360
169 2015-09-03  110.37  110.370000  43.500
170 2015-09-04  109.27  109.270000  42.610

[171 rows x 4 columns]

In [84]:
#删除指定列的重复值
data.drop_duplicates(['GOOG'])

          Date    GOOG        AAPL     SPX
0   2015-01-02  109.33  109.330000     NaN
1   2015-01-05  106.25  122.938765  46.325
2   2015-01-06  106.26  106.260000  45.650
3   2015-01-07  107.75  107.750000  46.230
4   2015-01-08  111.89  111.890000  47.590
..         ...     ...         ...     ...
166 2015-08-31  112.76  112.760000  43.520
167 2015-09-01  107.72  107.720000  41.820
168 2015-09-02  112.34  112.340000  43.360
169 2015-09-03  110.37  110.370000  43.500
170 2015-09-04  109.27  109.270000  42.610

[160 rows x 4 columns]

In [85]:
#删除指定列的重复值,保留重复行的最后一行
data.drop_duplicates(['GOOG'],keep='last')

          Date    GOOG        AAPL     SPX
0   2015-01-02  109.33  109.330000     NaN
1   2015-01-05  106.25  122.938765  46.325
2   2015-01-06  106.26  106.260000  45.650
3   2015-01-07  107.75  107.750000  46.230
4   2015-01-08  111.89  111.890000  47.590
..         ...     ...         ...     ...
166 2015-08-31  112.76  112.760000  43.520
167 2015-09-01  107.72  107.720000  41.820
168 2015-09-02  112.34  112.340000  43.360
169 2015-09-03  110.37  110.370000  43.500
170 2015-09-04  109.27  109.270000  42.610

[160 rows x 4 columns]

In [86]:
#删除重复值，保留副本
data.drop_duplicates(['GOOG'],inplace=False)
data

          Date    GOOG        AAPL     SPX
0   2015-01-02  109.33  109.330000     NaN
1   2015-01-05  106.25  122.938765  46.325
2   2015-01-06  106.26  106.260000  45.650
3   2015-01-07  107.75  107.750000  46.230
4   2015-01-08  111.89  111.890000  47.590
..         ...     ...         ...     ...
166 2015-08-31  112.76  112.760000  43.520
167 2015-09-01  107.72  107.720000  41.820
168 2015-09-02  112.34  112.340000  43.360
169 2015-09-03  110.37  110.370000  43.500
170 2015-09-04  109.27  109.270000  42.610

[171 rows x 4 columns]

# 异常值处理
什么是异常值 超出或者低于正常范围
异常值的检验 根据给定的范围 根据均方差 根据箱型图
异常值的处理 删除 当缺失值 当特殊情况分析

# 索引的设置
pandas索引的作用 方便查数据 使用索引可以提升查询性能
重新设置索引 df.reindex(labels=None,index=None,column=None,axis=None,method=None
设置某列为行索引 df.set_index()
数据清洗后重新设置连续的索引 df.reset_index()

In [87]:
s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([2,3,4],index=['a','b','c'])
s=s1+s2
s

a    12
b    23
c    34
dtype: int64

In [88]:
#Series重新设置索引
s=pd.Series([11,22,33],index=[1,2,3])
#重新设置索引
print(s.reindex(range(1,6)))#多出来2个nan
#使用0进行填充
print(s.reindex(range(1,6),fill_value=0))
#向前填充和向后填充
print(s.reindex(range(1,6),method='ffill'))#向前填充
print(s.reindex(range(1,6),method='bfill'))#向后填充

1    11.0
2    22.0
3    33.0
4     NaN
5     NaN
dtype: float64
1    11
2    22
3    33
4     0
5     0
dtype: int64
1    11
2    22
3    33
4    33
5    33
dtype: int64
1    11.0
2    22.0
3    33.0
4     NaN
5     NaN
dtype: float64

In [89]:
#DataFrame对象重新设置索引
data  = [[90,100,90],[100,39,89],[49,79,87]]
index = ['msb1001','msb1002','msb1003']
columns=['数学','语文','英语']
df = pd.DataFrame(data,index,columns)
df

         数学  语文  英语
msb1001    90   100    90
msb1002   100    39    89
msb1003    49    79    87

In [90]:
#重新设置索引 行和列
#行
print(df.reindex(['msb1001','msb1002','msb1003','msb1004','msb1005']))

          数学   语文  英语
msb1001   90.0  100.0  90.0
msb1002  100.0   39.0  89.0
msb1003   49.0   79.0  87.0
msb1004    NaN    NaN   NaN
msb1005    NaN    NaN   NaN

In [83]:
#列
print(df.reindex(columns=['数学','语文','英语','政治','历史']))

         数学  语文  英语  政治  历史
msb1001    90   100    90   NaN   NaN
msb1002   100    39    89   NaN   NaN
msb1003    49    79    87   NaN   NaN

In [84]:
#同时设置行和列
print(df.reindex(index=['msb1001','msb1002','msb1003','msb1004','msb1005'],columns=['数学','语文','英语','政治','历史'],fill_value=0))

         数学  语文  英语  政治  历史
msb1001    90   100    90     0     0
msb1002   100    39    89     0     0
msb1003    49    79    87     0     0
msb1004     0     0     0     0     0
msb1005     0     0     0     0     0

In [85]:
#设置某列为行索引
data = pd.read_excel('1.xlsx',header=0)
data

          Date    GOOG    AAPL     SPX
0   2015-01-02  109.33  109.33  46.760
1   2015-01-05  106.25  106.25  46.325
2   2015-01-06  106.26  106.26  45.650
3   2015-01-07  107.75  107.75  46.230
4   2015-01-08  111.89  111.89  47.590
..         ...     ...     ...     ...
166 2015-08-31  112.76  112.76  43.520
167 2015-09-01  107.72  107.72  41.820
168 2015-09-02  112.34  112.34  43.360
169 2015-09-03  110.37  110.37  43.500
170 2015-09-04  109.27  109.27  42.610

[171 rows x 4 columns]

In [86]:
data=data.set_index('Date')
data

              GOOG    AAPL     SPX
Date
2015-01-02  109.33  109.33  46.760
2015-01-05  106.25  106.25  46.325
2015-01-06  106.26  106.26  45.650
2015-01-07  107.75  107.75  46.230
2015-01-08  111.89  111.89  47.590
...            ...     ...     ...
2015-08-31  112.76  112.76  43.520
2015-09-01  107.72  107.72  41.820
2015-09-02  112.34  112.34  43.360
2015-09-03  110.37  110.37  43.500
2015-09-04  109.27  109.27  42.610

[171 rows x 3 columns]

In [87]:
#数据清洗
#1.先删除空值
data = pd.read_excel('1.xlsx',header=0)
data.iloc[2,3]=None
data.iloc[1,2]=None
#重新设置索引
data.dropna().reset_index(drop=True)

          Date    GOOG    AAPL    SPX
0   2015-01-02  109.33  109.33  46.76
1   2015-01-07  107.75  107.75  46.23
2   2015-01-08  111.89  111.89  47.59
3   2015-01-09  112.01  112.01  47.19
4   2015-01-12  109.25  109.25  46.60
..         ...     ...     ...    ...
164 2015-08-31  112.76  112.76  43.52
165 2015-09-01  107.72  107.72  41.82
166 2015-09-02  112.34  112.34  43.36
167 2015-09-03  110.37  110.37  43.50
168 2015-09-04  109.27  109.27  42.61

[169 rows x 4 columns]

# 数据的排序与排名
DataFrame排序时主要的方法·是sort_values()方法
df.sort_valuess(by,axis=0,ascending=True,inplace=False,kind='quicksort',na_position='last',ignore_index=True)
by 要排序的名称列表 axis=0为行 1表示列 
ascending 升序或者降序
kind 排序算法
na_position 空值的位置
ignore_index 布尔值 是否忽略索引

In [91]:
df=data.sort_values(by='AAPL')
df

AttributeError: 'list' object has no attribute 'sort_values'

In [89]:
#数据排名 使用rank方法
#df.rank(axis=0,method='average',ascending=True,na_option='keep')

In [90]:
 df['顺序排名'] = df['AAPL'].rank(ascending=False) # 默认采用顺序排名的平均值
df

          Date    GOOG    AAPL     SPX  顺序排名
161 2015-08-24  103.12  103.12  41.680     170.0
162 2015-08-25  103.74  103.74  40.470     169.0
160 2015-08-21  105.76  105.76  43.070     168.0
10  2015-01-16  105.99  105.99  46.240     167.0
2   2015-01-06  106.26  106.26     NaN     166.0
..         ...     ...     ...     ...       ...
35  2015-02-24  132.17  132.17  44.090       4.0
97  2015-05-22  132.54  132.54  46.900       3.0
78  2015-04-27  132.65  132.65  48.030       2.0
34  2015-02-23  133.00  133.00  44.150       1.0
1   2015-01-05  106.25     NaN  46.325       NaN

[171 rows x 5 columns]

# 数据计算
求和 sum
求均值 mean
最大值 max
最小值 min
中位数 media
众数 mode
方差 var
标准差 std
分为数 quantile

In [91]:
#行计算
data =[[100,77,88],[90,87,88],[67,77,99]]
columns = ['数学','语文','英语']
df = pd.DataFrame(data,columns=columns,index=[1,2,3])
df['总成绩']=df.sum(axis=1)
df['平均分'] = df[['语文', '数学', '英语']].mean(axis=1)

In [92]:
df

   数学  语文  英语  总成绩     平均分
1   100    77    88     265  88.333333
2    90    87    88     265  88.333333
3    67    77    99     243  81.000000

In [93]:
#列计算
df=df[['语文', '数学', '英语']]._append(df.mean(),ignore_index=True)
df

        语文        数学       英语      总成绩     平均分
0  77.000000  100.000000  88.000000         NaN        NaN
1  87.000000   90.000000  88.000000         NaN        NaN
2  77.000000   67.000000  99.000000         NaN        NaN
3  80.333333   85.666667  91.666667  257.666667  85.888889

In [94]:
#众数 列和行
data =[[100,77,88],[90,87,88],[90,77,99]]
columns = ['数学','语文','英语']
df = pd.DataFrame(data=data,columns=columns,index=[1,2,3])
df.mode()
print(df.mode())
print(df.mode(axis=1))
print(df['数学'].mode())

   数学  语文  英语
0    90    77    88
    0   1    2
1  77  88  100
2  87  88   90
3  77  90   99
0    90
Name: 数学, dtype: int64

In [95]:
#求方差
data = [[135,140,138,145,140],[140,145,139,142,132]]
index = ['李帆','张曙光']
columns=['一模','二模','三模','四模','五模']
df=pd.DataFrame(data,index,columns)
df.var(axis=1)

李帆      13.3
张曙光    23.3
dtype: float64

In [96]:
#求标准差
data = [[135,140,138,145,140],[140,145,139,142,132]]
index = ['李帆','张曙光']
columns=['一模','二模','三模','四模','五模']
df=pd.DataFrame(data,index,columns)
df.std(axis=0)

一模    3.535534
二模    3.535534
三模    0.707107
四模    2.121320
五模    5.656854
dtype: float64

In [97]:
#求分位数
data = [120,110,112,100,98,34,123,115]
columns = ['数学']
df = pd.DataFrame(data=data,columns=columns)
x=df['数学'].quantile(0.35)
print(x)
print(df[df['数学']<x])

104.5
   数学
3   100
4    98
5    34

# 数据格式化
设置小数位数 df.round()
设置百分比  appy() 与 format()
设置千位分隔符 appy() format()

In [98]:
import numpy as np
data = np.random.randn(4,5)
data

array([[-1.01823001, -0.57907709, -0.90342812, -0.14595988, -1.21871879],
       [-0.30341398, -0.27978052,  0.97313794,  0.79823256, -0.37311052],
       [-0.93164029,  1.10314484, -0.07944491,  0.71604436, -0.19975514],
       [-2.50361398,  0.64647034,  0.25347201, -0.25774097,  1.02056484]])

In [99]:
#保留小数尾数
columns =['1','2','3','4','5']
df = pd.DataFrame(data=data,columns=columns)
df.round({'1':1,'2':2,'3':3,'4':4,'5':5})

     1     2      3       4        5
0 -1.0 -0.58 -0.903 -0.1460 -1.21872
1 -0.3 -0.28  0.973  0.7982 -0.37311
2 -0.9  1.10 -0.079  0.7160 -0.19976
3 -2.5  0.65  0.253 -0.2577  1.02056

In [100]:
#设置百分比
df['百分比']=df['1'].apply(lambda x:format(x,'.0%')) #保留0位小数
df

          1         2         3         4         5 百分比
0 -1.018230 -0.579077 -0.903428 -0.145960 -1.218719  -102%
1 -0.303414 -0.279781  0.973138  0.798233 -0.373111   -30%
2 -0.931640  1.103145 -0.079445  0.716044 -0.199755   -93%
3 -2.503614  0.646470  0.253472 -0.257741  1.020565  -250%

In [101]:
df['百分比']=df['1'].apply(lambda x:format(x,'.2%')) #保留2位小数
df

          1         2         3         4         5    百分比
0 -1.018230 -0.579077 -0.903428 -0.145960 -1.218719  -101.82%
1 -0.303414 -0.279781  0.973138  0.798233 -0.373111   -30.34%
2 -0.931640  1.103145 -0.079445  0.716044 -0.199755   -93.16%
3 -2.503614  0.646470  0.253472 -0.257741  1.020565  -250.36%

In [102]:
#设置千位分割符
df=df.apply(lambda x:format(int(x),','))

TypeError: cannot convert the series to <class 'int'>

In [92]:
score = np.random.randint(50,100,(10,5))
score

NameError: name 'np' is not defined

In [ ]:
score_df = pd.DataFrame(score)

In [ ]:
score_df

In [ ]:
subjects = ['语文','数学','英语','政治','体育']
stu = ['同学'+str(i) for i in range(score_df.shape[0])]
data = pd.DataFrame(score,index=stu,columns=subjects)
data

# multilndex特性

In [ ]:
#创建arrays
arrays = [[1,1,2,2],['red','blue','red','blue']]
pd.MultiIndex.from_arrays(arrays,names=('number','color'))

In [ ]:
df['1']

数据表的拼接

In [104]:
left = pd.DataFrame({'key1':['k0','k0','k1','k2'],
                    'key2':['k0','k1','k0','k1'],
                    'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3']})
right = pd.DataFrame({'key1':['k0','k1','k1','k2'],
                    'key2':['k0','k0','k0','k0'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']})

In [106]:
pd.merge(left,right,on=['key1','key2'])

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A2  B2  C1  D1
2   k1   k0  A2  B2  C2  D2

In [107]:
pd.merge(left,right,on=['key1','key2'],how='inner')

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k0  A2  B2  C1  D1
2   k1   k0  A2  B2  C2  D2

In [108]:
pd.merge(left,right,on=['key1','key2'],how='left')

  key1 key2   A   B    C    D
0   k0   k0  A0  B0   C0   D0
1   k0   k1  A1  B1  NaN  NaN
2   k1   k0  A2  B2   C1   D1
3   k1   k0  A2  B2   C2   D2
4   k2   k1  A3  B3  NaN  NaN

In [109]:
pd.merge(left,right,on=['key1','key2'],how='right')

  key1 key2    A    B   C   D
0   k0   k0   A0   B0  C0  D0
1   k1   k0   A2   B2  C1  D1
2   k1   k0   A2   B2  C2  D2
3   k2   k0  NaN  NaN  C3  D3

In [114]:
#分组和聚合
col = pd.DataFrame({'color':['white','red','green','red','green'],
                   'object':['pen','pencil','pencil','ashtray','pen'],
                   'price1':[5.56,4.20,1.30,0.56,2.75],
                   'price2':[4.75,4.12,1.60,0.75,3.15] })
col

   color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [116]:
col.groupby(['color'])['price1'].mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [117]:
col.groupby(['color'],as_index=False)['price1'].mean()

   color  price1
0  green   2.025
1    red   2.380
2  white   5.560