In [1]:
import pandas as pd

In [6]:
import pandas as pd  # 先确保导入pandas（很多新手会漏这行）
df = pd.read_csv('C:\\Users\\86157\\Desktop\\实例股票数据.csv', encoding='gbk')
print(df)

          日期   开盘价   收盘价   最低价   最高价        成交量
0   2020/1/1  50.2  51.5  49.8  52.1  1000000.0
1   2020/1/2  52.0  53.2  51.5  54.0  1200000.0
2   2020/1/3  54.5   NaN  53.8  56.0  -500000.0
3   2020/1/4  55.2  53.8  52.5  55.5   900000.0
4   2020/1/5  54.0  53.2  52.1  54.8  1100000.0
5   2020/1/6  53.5  52.7  51.8  54.2   950000.0
6   2020/1/7  52.8  54.3  52.4  55.1   800000.0
7   2020/1/8  54.2  55.6   NaN  56.2   750000.0
8   2020/1/9  55.7  56.2  54.9  56.5   850000.0
9  2020/1/10  56.0  55.5  54.7  56.8        NaN

In [9]:
#查看缺少值
missing_values = df.isna().sum()
print('缺失值的数量:',missing_values)

缺失值的数量: 日期     0
开盘价    0
收盘价    1
最低价    1
最高价    0
成交量    1
dtype: int64

### 填充缺失值

In [11]:
#使用平均值填充收盘价
mean_close  = df['收盘价'].mean()
print(mean_close)
df['收盘价'].fillna(mean_close,inplace=True)
print(df['收盘价'])

54.0
0    51.5
1    53.2
2    54.0
3    53.8
4    53.2
5    52.7
6    54.3
7    55.6
8    56.2
9    55.5
Name: 收盘价, dtype: float64

In [12]:
#使用中位数填充最低价
median_low = df['最低价'].median()
print(median_low)
df['最低价'].fillna(median_low,inplace=True)
print(df['最低价'])

52.4
0    49.8
1    51.5
2    53.8
3    52.5
4    52.1
5    51.8
6    52.4
7    52.4
8    54.9
9    54.7
Name: 最低价, dtype: float64

In [16]:
#用临近值填充最高价
df['最高价'].fillna(method='ffill',inplace=True)
print(df['最高价'])

0    52.1
1    54.0
2    56.0
3    55.5
4    54.8
5    54.2
6    55.1
7    56.2
8    56.5
9    56.8
Name: 最高价, dtype: float64

In [18]:
#用0填充成交量
df['成交量'].fillna(0,inplace=True)
print(df['成交量'])

0    1000000.0
1    1200000.0
2    -500000.0
3     900000.0
4    1100000.0
5     950000.0
6     800000.0
7     750000.0
8     850000.0
9          0.0
Name: 成交量, dtype: float64

In [19]:
#查看填充完成的DF
df

          日期   开盘价   收盘价   最低价   最高价        成交量
0   2020/1/1  50.2  51.5  49.8  52.1  1000000.0
1   2020/1/2  52.0  53.2  51.5  54.0  1200000.0
2   2020/1/3  54.5  54.0  53.8  56.0  -500000.0
3   2020/1/4  55.2  53.8  52.5  55.5   900000.0
4   2020/1/5  54.0  53.2  52.1  54.8  1100000.0
5   2020/1/6  53.5  52.7  51.8  54.2   950000.0
6   2020/1/7  52.8  54.3  52.4  55.1   800000.0
7   2020/1/8  54.2  55.6  52.4  56.2   750000.0
8   2020/1/9  55.7  56.2  54.9  56.5   850000.0
9  2020/1/10  56.0  55.5  54.7  56.8        0.0

### 修改数据类型

In [20]:
#日期格式转换
df['日期'] =pd.to_datetime(df['日期'])
df['日期'].dtype

dtype('<M8[ns]')

In [21]:
#转换为数值类型
numeric_cols = ['开盘价','收盘价','最高价','最低价','成交量']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)
df

          日期   开盘价   收盘价   最低价   最高价        成交量
0 2020-01-01  50.2  51.5  49.8  52.1  1000000.0
1 2020-01-02  52.0  53.2  51.5  54.0  1200000.0
2 2020-01-03  54.5  54.0  53.8  56.0  -500000.0
3 2020-01-04  55.2  53.8  52.5  55.5   900000.0
4 2020-01-05  54.0  53.2  52.1  54.8  1100000.0
5 2020-01-06  53.5  52.7  51.8  54.2   950000.0
6 2020-01-07  52.8  54.3  52.4  55.1   800000.0
7 2020-01-08  54.2  55.6  52.4  56.2   750000.0
8 2020-01-09  55.7  56.2  54.9  56.5   850000.0
9 2020-01-10  56.0  55.5  54.7  56.8        0.0

In [25]:
#数值利列数据类型转
df['开盘价']  =df['开盘价'].astype(float)
df['开盘价'].dtype

dtype('float64')

### 异常值处理

In [27]:
# 步骤1：先计算“成交量为负”的数据（先赋值，再判断，避免提前引用）
negative_volume = df[df['成交量'] < 0]

# 步骤2：正确的if判断格式（冒号+缩进）
if not negative_volume.empty:  # 现在negative_volume已定义，可正常判断是否为空
    print('存在异常值,成交量为负数')
    print(negative_volume)  # 缩进：这行属于if分支，必须缩进

# 步骤3：将负数成交量改为None（这步逻辑没问题，可保留）
df.loc[df['成交量'] < 0, '成交量'] = None  # 注意：None在pandas中会被识别为缺失值

# 步骤4：查看处理后的数据（建议增加“缺失值数量”的打印，验证处理效果）
print('处理后的DF:')
print(df)
print('成交量列的缺失值数量:', df['成交量'].isnull().sum())  # 可选：验证负数是否已转为None

存在异常值,成交量为负数
          日期   开盘价   收盘价   最低价   最高价       成交量
2 2020-01-03  54.5  54.0  53.8  56.0 -500000.0
处理后的DF:
          日期   开盘价   收盘价   最低价   最高价        成交量
0 2020-01-01  50.2  51.5  49.8  52.1  1000000.0
1 2020-01-02  52.0  53.2  51.5  54.0  1200000.0
2 2020-01-03  54.5  54.0  53.8  56.0        NaN
3 2020-01-04  55.2  53.8  52.5  55.5   900000.0
4 2020-01-05  54.0  53.2  52.1  54.8  1100000.0
5 2020-01-06  53.5  52.7  51.8  54.2   950000.0
6 2020-01-07  52.8  54.3  52.4  55.1   800000.0
7 2020-01-08  54.2  55.6  52.4  56.2   750000.0
8 2020-01-09  55.7  56.2  54.9  56.5   850000.0
9 2020-01-10  56.0  55.5  54.7  56.8        0.0
成交量列的缺失值数量: 1