# 数据持久化

In [1]:
#文件的打开与关闭
# f = open(file_name,mode='r',encoding=None)
# file_name:文件名称
# mode:文件的打开模式:只读,写入,追加等
# encoding:编码方式.默认不指定

## 从文件中读

In [7]:
with open('hello.txt', 'w', encoding='utf-8') as file:
    file.write('Hello World!  \n Hello Python!')

In [8]:
f = open(r'./hello.txt')

In [9]:
#读全部内容
f.read()

'Hello World!  \n Hello Python!'

In [10]:
f.read()

''

In [11]:
f.close()

In [12]:
#读一行
f = open('hello.txt','r')
f.readline()

'Hello World!  \n'

In [13]:
f.readline()

' Hello Python!'

In [14]:
f.close()

In [15]:
f = open('hello.txt','r')
for line in f:
    print(line,end='')

Hello World!
 Hello Python!

In [16]:
f.close()

In [17]:
#按行读所有的内容
f = open('hello.txt','r')
li = f.readlines()
li

['Hello World!  \n', ' Hello Python!']

In [18]:
with open('poem.txt', 'w', encoding='utf-8') as file:
    file.write('剑客 . 贾岛\n 十年磨一剑,霜刃未曾试.\n 今日把示君,谁有不平事.')

In [21]:
f = open('poem.txt','r',encoding='utf-8')

In [22]:
f.read()

'剑客 . 贾岛\n 十年磨一剑,霜刃未曾试.\n 今日把示君,谁有不平事.'

## 写文件

In [23]:
f = open('hello.txt','w',encoding='utf-8')
f.write('Hello\n')

6

In [24]:
f.write('半朽临风树,多情立马人.')

12

In [25]:
f.close()

## 文件指针

In [26]:
f = open('hello.txt','wb+')
f.write(b'0123456789abcdef')

16

In [27]:
f.seek(5)#定位到第六个字符

5

In [28]:
f.read(1)

b'5'

In [29]:
f.seek(-3,2) #定位到倒数第三个字符

13

In [30]:
f.read(1)

b'd'

In [31]:
f.close()

# CSV文件

In [51]:
import tushare as ts
import pandas as pd

# 设置tushare token
ts.set_token('598eb3c437b4143dde41a08f283e909b5cce0154bb923c346d4c6e58')

# 初始化接口
pro = ts.pro_api()

# 获取股票历史数据（600000.SH 为浦发银行）
df = pro.daily(ts_code='600000.SH', start_date='20200101', end_date='20200108')

# 按日期排序并设置日期为索引
df = df.sort_values(by='trade_date')  # 按交易日期升序排列
df = df.set_index('trade_date')       # 将交易日期设置为索引（注意这里需要赋值）

# 选择需要的列
df = df[['open', 'close', 'high', 'low']]

# 显示数据
df

             open  close   high    low
trade_date
20200102    12.47  12.47  12.64  12.45
20200103    12.57  12.60  12.63  12.47
20200106    12.52  12.46  12.65  12.42
20200107    12.51  12.50  12.60  12.46
20200108    12.41  12.32  12.45  12.25

In [42]:
df.to_csv(r'.\stock_data.csv')

In [43]:
import pandas as pd
stock_data = pd.read_csv('./stock_data.csv',index_col=0)
stock_data

             open  close   high    low
trade_date
20200102    12.47  12.47  12.64  12.45
20200103    12.57  12.60  12.63  12.47
20200106    12.52  12.46  12.65  12.42
20200107    12.51  12.50  12.60  12.46
20200108    12.41  12.32  12.45  12.25

## 读取csv

In [45]:
import csv
with open('./stock_data.csv','r') as f:
    f_csv = csv.reader(f)
    for line in f_csv:
        print(line)

['trade_date', 'open', 'close', 'high', 'low']
['20200102', '12.47', '12.47', '12.64', '12.45']
['20200103', '12.57', '12.6', '12.63', '12.47']
['20200106', '12.52', '12.46', '12.65', '12.42']
['20200107', '12.51', '12.5', '12.6', '12.46']
['20200108', '12.41', '12.32', '12.45', '12.25']

## 写csv文件

In [54]:
# 关键：恢复Python内置的open()函数（解决被覆盖的问题）
import builtins
open = builtins.open  # 将open重新指向内置函数

# 然后再运行完整的股票数据获取和写入代码
import csv
import tushare as ts

# 1. 初始化Tushare
ts.set_token('598eb3c437b4143dde41a08f283e909b5cce0154bb923c346d4c6e58')
pro = ts.pro_api()

# 2. 获取数据
df = pro.daily(ts_code='600000.SH', start_date='20200101', end_date='20200108')

# 3. 数据预处理
df = df.sort_values(by='trade_date').set_index('trade_date')  # 链式调用更简洁
df = df[['open', 'close', 'high', 'low']]

# 4. 写入CSV（此时open()已恢复为内置函数，不会报错）
with open(r'./stock_data.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['date', 'open', 'close', 'high', 'low'])  # 表头
    for date, row in df.iterrows():
        # 提取数据（用明确的列名，避免歧义）
        row_data = [date, row['open'], row['close'], row['high'], row['low']]
        writer.writerow(row_data)

print("CSV文件已保存！")
# 验证：读取CSV确认结果
import pandas as pd
print("\nCSV文件内容：")
print(pd.read_csv('./stock_data.csv'))

CSV文件已保存！

CSV文件内容：
       date   open  close   high    low
0  20200102  12.47  12.47  12.64  12.45
1  20200103  12.57  12.60  12.63  12.47
2  20200106  12.52  12.46  12.65  12.42
3  20200107  12.51  12.50  12.60  12.46
4  20200108  12.41  12.32  12.45  12.25

# SQl数据库

## 连接,关闭数据库

In [55]:
import sqlite3
conn = sqlite3.connect('test.db')
if conn:
    print('连接数据库成功')
conn.close()

连接数据库成功

## 创建表

In [56]:
import sqlite3
conn = sqlite3.connect('test.db')
c = conn.cursor()
c.execute('''CREATE TABLE EMP
       (ID INT PRIMSRY KEY   NOT NULL,
        NAME           TEXT  NOT NULL,
        AGE            INT   NOT NULL,
        SALARY         REAL)''')
conn.close()

## 插入数据

In [60]:
import sqlite3

# 连接到SQLite数据库（如果不存在则创建）
conn = sqlite3.connect('test.db')

# 创建一个游标对象
c = conn.cursor()

# 先创建表（如果不存在）
c.execute('''CREATE TABLE IF NOT EXISTS EMP
             (ID INT PRIMARY KEY     NOT NULL,
             NAME           TEXT    NOT NULL,
             AGE            INT     NOT NULL,
             SALARY         REAL);''')

# 插入数据，使用双引号包裹字符串值
c.execute('INSERT INTO EMP (ID,NAME,AGE,SALARY) \
            VALUES(1,"ZHANG",28,160000)');
c.execute('INSERT INTO EMP (ID,NAME,AGE,SALARY)\
            VALUES(2,"ZHANG",28,160000)');
c.execute('INSERT INTO EMP (ID,NAME,AGE,SALARY)\
            VALUES(3,"ZHANG",28,160000)');

# 提交事务
conn.commit()

# 验证插入结果
c.execute("SELECT * FROM EMP")
print("插入的记录:")
for row in c.fetchall():
    print(row)

# 关闭数据库连接
conn.close()

插入的记录:
(1, 'ZHANG', 28, 160000.0)
(2, 'ZHANG', 28, 160000.0)
(3, 'ZHANG', 28, 160000.0)

## 查询数据

In [61]:
import sqlite3
conn = sqlite3.connect('test.db')
c = conn.cursor()
cursor = c.execute('SELECT * from EMP')
for row in cursor:
    print(row[1],row[2],row[3],sep='')

ZHANG28160000.0
ZHANG28160000.0
ZHANG28160000.0

## 修改数据

In [63]:
import sqlite3

# 连接到数据库
conn = sqlite3.connect('test.db')
c = conn.cursor()

# 更新数据 - 使用双引号包裹SQL中的字符串，避免与Python的单引号冲突
c.execute('UPDATE EMP set SALARY = 20000 where NAME = "ZHANG"')
conn.commit()  # 提交更新

# 查询更新后的数据
# 同样使用双引号包裹查询条件中的字符串
cursor = conn.execute('SELECT * from EMP where NAME = "ZHANG"')

# 打印查询结果
print("更新后的员工信息（姓名 年龄 工资）：")
for row in cursor:
    # 打印姓名、年龄、工资，用空格分隔
    print(row[1], row[2], row[3], sep=' ')

# 关闭数据库连接
conn.close()

更新后的员工信息（姓名 年龄 工资）：
ZHANG 28 20000.0
ZHANG 28 20000.0
ZHANG 28 20000.0

## 删除数据

In [65]:
import sqlite3
conn = sqlite3.connect('test.db')
c = conn.cursor()
c.execute("DELETE from EMP where ID='2'")
conn.commit()
cursor = c.execute("SELECT * from EMP")
for row in cursor:
    print(row[1],row[2],row[3])

ZHANG 28 20000.0
ZHANG 28 20000.0