## 基础题

In [2]:
import numpy as np
import pandas as pd

### 将下列的字典创建为DataFrame

In [3]:
data = {
    'grammer' : ['Python','C','Java','GO',np.nan,'SOL','PHP','Python'],
    'score' : [1,2,np.nan,4,5,6,7,10]
}

In [5]:
df = pd.DataFrame(data)
df

  grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     NaN    5.0
5     SOL    6.0
6     PHP    7.0
7  Python   10.0

### 提取含有字符串’Python‘的行

In [6]:
#方法一
df[df['grammer'] == 'Python']

  grammer  score
0  Python    1.0
7  Python   10.0

In [7]:
#方法二
results = df['grammer'].str.contains('Python')
results.fillna(value=False,inplace=True)
df[results]

C:\Users\86157\AppData\Local\Temp\ipykernel_6456\111610703.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  results.fillna(value=False,inplace=True)

  grammer  score
0  Python    1.0
7  Python   10.0

### 输出df所有的列名

In [9]:
df.columns

Index(['grammer', 'score'], dtype='object')

### 修改第二列列名为’popularity‘

In [10]:
df.rename(columns= {'score':'popularity'},inplace=True)
df

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         NaN
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0
7  Python        10.0

### 统计grammer列中每种汇编语言出现的次数

In [12]:
df.grammer.value_counts()

grammer
Python    2
C         1
Java      1
GO        1
SOL       1
PHP       1
Name: count, dtype: int64

### 将空值用上下值的平均值填充

通常方法(直接写逻辑,并分别用df.at,df.loc,df.iloc完成赋值操作)

In [14]:
df1 = df[:].copy()
#发现null值,返回逻辑值
null_values = df1['popularity'].isnull()
for i in range(1,len(df1)-1): #因为是上下值填充所有需要限制范围
    if null_values[i]:#i=True表示空值,需要填充
        avg = (df1.at[i-1,'popularity'] + df1.at[i+1,'popularity']) / 2
        df1.at[i,'popularity'] = avg
print(df1)

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0
7  Python        10.0

In [15]:
#简单方法
df['popularity'] = df['popularity'].fillna(df['popularity'].interpolate())
df

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0
7  Python        10.0

### 提取popularity中值大于3的行

In [16]:
df[df['popularity'] > 3]

  grammer  popularity
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0
7  Python        10.0

### 按照grammer排序,去除重复值

In [17]:
df.drop_duplicates(subset= ['grammer'])

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0

### 计算popularity的平均值

In [19]:
df['popularity'].mean()

4.75

### 将grammer列转换为list

In [20]:
#返回的是list
df['grammer'].to_list()

['Python', 'C', 'Java', 'GO', nan, 'SOL', 'PHP', 'Python']

In [22]:
#返回的是array
df['grammer'].values

array(['Python', 'C', 'Java', 'GO', nan, 'SOL', 'PHP', 'Python'],
      dtype=object)

### 将DF保存为excel

In [23]:
df.to_excel('语法及流行程度.xlsx',index=False)

### 查看数据的行列数

In [24]:
df.shape

(8, 2)

## 提取popularity列值大于3小于7的行

In [28]:
df[(df['popularity']>3) & (df['popularity'] <7)]

  grammer  popularity
3      GO         4.0
4     NaN         5.0
5     SOL         6.0

### 交换两列的位置

In [29]:
#法一
temp = df['popularity']
df.drop(labels=['popularity'],axis=1,inplace=True)
df.insert(0,'popularity',temp)
df

   popularity grammer
0         1.0  Python
1         2.0       C
2         3.0    Java
3         4.0      GO
4         5.0     NaN
5         6.0     SOL
6         7.0     PHP
7        10.0  Python

In [30]:
#法二
cols = df.columns[[1,0]]
df = df[cols]
df

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0
7  Python        10.0

### 提取popularity列最大值所在的行

In [41]:
df[df['popularity'] == df['popularity'].max()].index.values[0]

7

### 查看最后5行的数据

In [42]:
df.tail()

  grammer  popularity
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0
7  Python        10.0

In [43]:
### 删除最后一行的数据

In [44]:
df.drop(len(df)-1,inplace=True)
df

C:\Users\86157\AppData\Local\Temp\ipykernel_6456\2316962633.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(len(df)-1,inplace=True)

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0

### 添加一行数据['Perl',6.6]

In [46]:
row = {'grammer': 'Perl','popularity': 6.6}
df = df._append(row,ignore_index = True)
df

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
6     PHP         7.0
7    Perl         6.6

### 对数据按照'popularity'列值的大小进行排序

In [47]:
df.sort_values(by=['popularity'],inplace=True)
df

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         3.0
3      GO         4.0
4     NaN         5.0
5     SOL         6.0
7    Perl         6.6
6     PHP         7.0

### 统计grammer列每个字符串的长度

In [53]:
df['grammer'].fillna('R',inplace=True)
df['str_len'] = df['grammer'].str.len()
df

  grammer  popularity  str_len
0  Python         1.0        6
1       C         2.0        1
2    Java         3.0        4
3      GO         4.0        2
4       R         5.0        1
5     SOL         6.0        3
7    Perl         6.6        4
6     PHP         7.0        3