# 级联操作

In [1]:
import pandas as pd
import numpy as np

In [6]:
df1 = pd.DataFrame(data=np.random.randint(0,100,(5,3)),columns=['a','b','c'])
df2 = pd.DataFrame(data=np.random.randint(0,100,(5,3)),columns=['a','d','c'])

In [7]:
pd.concat((df1,df2),axis=1)#按列相连

    a   b   c   a   d   c
0   9  78  81  24  13  98
1   6  67  50   7  75  54
2  21  18  45  73  13  15
3  98  96  55  26  42  56
4  58   9  97  96  16  94

In [10]:
pd.concat((df1,df2),axis=0)#外连接显示所有的数据

    a     b   c     d
0   9  78.0  81   NaN
1   6  67.0  50   NaN
2  21  18.0  45   NaN
3  98  96.0  55   NaN
4  58   9.0  97   NaN
0  24   NaN  98  13.0
1   7   NaN  54  75.0
2  73   NaN  15  13.0
3  26   NaN  56  42.0
4  96   NaN  94  16.0

In [11]:
pd.concat((df1,df2),axis=0,join='inner')#内连接消除了有空值的列

    a   c
0   9  81
1   6  50
2  21  45
3  98  55
4  58  97
0  24  98
1   7  54
2  73  15
3  26  56
4  96  94

In [14]:
df1._append(df2)#按行相连与外连接一致

    a     b   c     d
0   9  78.0  81   NaN
1   6  67.0  50   NaN
2  21  18.0  45   NaN
3  98  96.0  55   NaN
4  58   9.0  97   NaN
0  24   NaN  98  13.0
1   7   NaN  54  75.0
2  73   NaN  15  13.0
3  26   NaN  56  42.0
4  96   NaN  94  16.0

# 合并操作

In [15]:
df1 = pd.DataFrame({'employee':['Lisa','BOb','Jake'],
                   'group':['Accounting','Engineering','Engineering']})
df1

  employee        group
0     Lisa   Accounting
1      BOb  Engineering
2     Jake  Engineering

In [16]:
df2 = pd.DataFrame({'employee':['Lisa','BOb','Jake'],
                   'hire_date':[2004,2008,2012]})
df2

  employee  hire_date
0     Lisa       2004
1      BOb       2008
2     Jake       2012

In [18]:
pd.merge(df1,df2,on='employee')

  employee        group  hire_date
0     Lisa   Accounting       2004
1      BOb  Engineering       2008
2     Jake  Engineering       2012