In [1]:
import pandas as pd
import numpy as np

# 替换操作

In [2]:
df = pd.DataFrame(data=np.random.randint(0,100,(5,6)))
df

    0   1   2   3   4   5
0   0   1  88  91  39   5
1  92  17  27  10  19  73
2  27  52  49  34  38   4
3  55  95  39   5  86  35
4  65  67   6  44   5  88

In [4]:
df.replace(to_replace=1,value='two')

    0    1   2   3   4   5
0   0  two  88  91  39   5
1  92   17  27  10  19  73
2  27   52  49  34  38   4
3  55   95  39   5  86  35
4  65   67   6  44   5  88

In [5]:
df.replace(to_replace={5:'five'})

    0   1   2     3     4     5
0   0   1  88    91    39  five
1  92  17  27    10    19    73
2  27  52  49    34    38     4
3  55  95  39  five    86    35
4  65  67   6    44  five    88

In [6]:
df.replace(to_replace={4,1},value='one')

    0    1   2   3   4    5
0   0  one  88  91  39    5
1  92   17  27  10  19   73
2  27   52  49  34  38  one
3  55   95  39   5  86   35
4  65   67   6  44   5   88

In [8]:
df.replace(to_replace=[4,1],value='one')

    0    1   2   3   4    5
0   0  one  88  91  39    5
1  92   17  27  10  19   73
2  27   52  49  34  38  one
3  55   95  39   5  86   35
4  65   67   6  44   5   88

# 映射

In [11]:
dic = {
    'name':['张三','李四','张三'],
    'salary':[15000,20000,15000]
}
df = pd.DataFrame(data=dic)
df

  name  salary
0   张三   15000
1   李四   20000
2   张三   15000

In [14]:
#映射关系表
dic = {
    '张三':'tom',
    '李四':'jack'
}
df['e_name']=df['name'].map(dic)
df

  name  salary e_name
0   张三   15000    tom
1   李四   20000   jack
2   张三   15000    tom

In [16]:
def after_sal(s):
    return s - (s-3000)*0.5

In [19]:
df['after_sal'] = df['salary'].map(after_sal)#充当运算工具
df

  name  salary e_name  after_sal
0   张三   15000    tom     9000.0
1   李四   20000   jack    11500.0
2   张三   15000    tom     9000.0

# 排序实现的随机抽样

In [22]:
df = pd.DataFrame(data=np.random.randint(0,100,(100,3)),columns=['A','B','C'])
df

     A   B   C
0   42  44  17
1   95  65  67
2   20  32  31
3   13  64  18
4   10  64  99
..  ..  ..  ..
95  98  26  32
96  69  42  29
97  13  89  11
98  31  32  61
99  54  93  96

[100 rows x 3 columns]

In [24]:
#生成随机的乱序
np.random.permutation(10)

array([8, 1, 9, 2, 6, 5, 4, 0, 3, 7])

In [27]:
#将原始数据打乱
df.take(np.random.permutation(3),axis=1).take(np.random.permutation(100),axis=0)[0:50]

     C   A   B
64  86  49  86
18  13  60  39
7   46  61  86
95  32  98  26
68  47  81  56
45   0  47  36
5   51  87   7
41   4  85   2
65  49  57  53
9   16   3  73
33  21  50   1
88   2  35  86
61  91  28   1
52  35  34  61
67  15   8  98
89  50  78  15
75  90  15  22
82  48  42  63
32  23  20   0
97  11  13  89
72  64  59  63
21  75  14   8
55  90  89  37
23  92  56  15
48   1  37  61
78  98  17   0
4   99  10  64
98  61  31  32
74  70  24  78
2   31  20  32
90  65  32  18
86  52  18  61
40  61  30  77
28  18  29   8
1   67  95  65
84  65   3  58
47  89  49  61
66  33   3  68
46  30  92  54
0   17  42  44
19  10   7  99
54   7  85  87
22  78  88  65
91   3  67   8
20   4  40  27
37   9  78  15
8    3  82  23
92  52  53  59
14   7  51  51
13  13  82  84

# 数据分类处理--分组聚合

In [29]:
df = pd.DataFrame({'item':['Apple','Banana','Orange','Banana','Orange','Apple'],
                   'price':[4,3,3,2.5,4,2],
                   'color':['red','yellow','yellow','green','green','green'],
                   'weight':[12,20,50,30,20,44]
})
df

     item  price   color  weight
0   Apple    4.0     red      12
1  Banana    3.0  yellow      20
2  Orange    3.0  yellow      50
3  Banana    2.5   green      30
4  Orange    4.0   green      20
5   Apple    2.0   green      44

In [33]:
df.groupby(by='item')['price'].mean()

item
Apple     3.00
Banana    2.75
Orange    3.50
Name: price, dtype: float64

In [34]:
df.groupby(by='item')['weight'].mean()

item
Apple     28.0
Banana    25.0
Orange    35.0
Name: weight, dtype: float64

In [37]:
dic = df.groupby(by='color')['weight'].mean().to_dict()
df['mean_col'] = df['color'].map(dic)
df

     item  price   color  weight   mean_col
0   Apple    4.0     red      12  12.000000
1  Banana    3.0  yellow      20  35.000000
2  Orange    3.0  yellow      50  35.000000
3  Banana    2.5   green      30  31.333333
4  Orange    4.0   green      20  31.333333
5   Apple    2.0   green      44  31.333333