# 缺失值处理

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame(data=np.random.randint(0,100,(8,6)))
df.iloc[2,3]=None
df.iloc[4,4]=None
df.iloc[5,2]=None
df

    0   1     2     3     4   5
0   1  26  37.0  50.0  18.0  29
1  38  35  60.0  12.0   9.0  25
2  51  57  85.0   NaN  55.0  78
3  76   7  30.0  75.0  63.0  54
4  99  11  55.0  31.0   NaN  76
5  83  69   NaN  74.0  59.0  33
6   6  83  76.0  44.0  95.0  83
7  97  17  40.0   4.0  45.0   2

方法一:对空值进行过滤（删除空值所在的行数据)

In [4]:
df.isnull()

       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False   True  False  False
3  False  False  False  False  False  False
4  False  False  False  False   True  False
5  False  False   True  False  False  False
6  False  False  False  False  False  False
7  False  False  False  False  False  False

In [8]:
df.isnull().any(axis=1)#检测每个行是否有空值
df.loc[df.isnull().any(axis=1)]#缺失行的行数据
drop_index = df.loc[df.isnull().any(axis=1)].index#缺失值行的行索引
df.drop(drop_index)

    0   1     2     3     4   5
0   1  26  37.0  50.0  18.0  29
1  38  35  60.0  12.0   9.0  25
3  76   7  30.0  75.0  63.0  54
6   6  83  76.0  44.0  95.0  83
7  97  17  40.0   4.0  45.0   2

In [11]:
df.notnull().all(axis=1)

0     True
1     True
2    False
3     True
4    False
5    False
6     True
7     True
dtype: bool

方法二：dropna

In [13]:
df.dropna(axis=0)

    0   1     2     3     4   5
0   1  26  37.0  50.0  18.0  29
1  38  35  60.0  12.0   9.0  25
3  76   7  30.0  75.0  63.0  54
6   6  83  76.0  44.0  95.0  83
7  97  17  40.0   4.0  45.0   2

# 对缺失值进行覆盖

In [16]:
df.fillna(method='ffill',axis=1)#水平方向向前填充

C:\Users\86157\AppData\Local\Temp\ipykernel_12908\2272395643.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',axis=1)

      0     1     2     3     4     5
0   1.0  26.0  37.0  50.0  18.0  29.0
1  38.0  35.0  60.0  12.0   9.0  25.0
2  51.0  57.0  85.0  85.0  55.0  78.0
3  76.0   7.0  30.0  75.0  63.0  54.0
4  99.0  11.0  55.0  31.0  31.0  76.0
5  83.0  69.0  69.0  74.0  59.0  33.0
6   6.0  83.0  76.0  44.0  95.0  83.0
7  97.0  17.0  40.0   4.0  45.0   2.0

In [18]:
df.fillna(method='bfill',axis=1)#水平方向向后填充

C:\Users\86157\AppData\Local\Temp\ipykernel_12908\1262483233.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',axis=1)#水平方向向后填充

      0     1     2     3     4     5
0   1.0  26.0  37.0  50.0  18.0  29.0
1  38.0  35.0  60.0  12.0   9.0  25.0
2  51.0  57.0  85.0  55.0  55.0  78.0
3  76.0   7.0  30.0  75.0  63.0  54.0
4  99.0  11.0  55.0  31.0  76.0  76.0
5  83.0  69.0  74.0  74.0  59.0  33.0
6   6.0  83.0  76.0  44.0  95.0  83.0
7  97.0  17.0  40.0   4.0  45.0   2.0

# 重复值处理

In [21]:
df = pd.DataFrame(data=np.random.randint(0,100,(8,4)))
df.iloc[2]=[0,0,0,0]
df.iloc[4]=[0,0,0,0]
df.iloc[5]=[0,0,0,0]

In [22]:
#使用drop_duplicates(keep='first')
df.drop_duplicates(keep='first')

    0   1   2   3
0  33  53  58  81
1  58  32  52  78
2   0   0   0   0
3  21  11  77  20
6  29  74  72   1
7  13  84  79  29

# 异常值的处理

In [28]:
df = pd.DataFrame(data=np.random.random((1000,3)),columns=['A','B','C'])
twice_std = df['C'].std()*2#异常值判断条件
df.loc[~(df['C']>twice_std)#取反]

            A         B         C
6    0.135814  0.174932  0.545209
8    0.845937  0.272755  0.084077
9    0.832413  0.518499  0.506710
10   0.447299  0.098940  0.334844
12   0.558669  0.371179  0.233214
..        ...       ...       ...
994  0.190207  0.227671  0.318941
995  0.948480  0.397854  0.184253
996  0.670877  0.142173  0.512133
998  0.001015  0.182128  0.545932
999  0.115353  0.461702  0.524290

[545 rows x 3 columns]