In [1]:
import tushare as ts
import pandas as pd
import  numpy as np
import datetime

ModuleNotFoundError: No module named 'tushare'

In [ ]:
ts.set_token('598eb3c437b4143dde41a08f283e909b5cce0154bb923c346d4c6e58')
pro = ts.pro_api()
pro = ts.pro_api('598eb3c437b4143dde41a08f283e909b5cce0154bb923c346d4c6e58')
# 拉取数据
df = pro.daily(**{
    "ts_code": "600519.SH",
    "trade_date": "",
    "start_date": "2000-01-01",
    "end_date": "2024-01-01",
    "offset": "",
    "limit": ""
}, fields=[
    "ts_code",
    "trade_date",
    "open",
    "high",
    "low",
    "close"
])
print(df)

In [170]:
df = df.sort_values(by='trade_date',ascending=True)
df

        ts_code trade_date     open     high      low    close
5348  600519.SH   20010827    34.51    37.78    32.85    35.55
5347  600519.SH   20010828    34.99    37.00    34.61    36.86
5346  600519.SH   20010829    36.98    37.00    36.10    36.38
5345  600519.SH   20010830    36.28    37.51    36.00    37.10
5344  600519.SH   20010831    37.15    37.62    36.80    37.01
...         ...        ...      ...      ...      ...      ...
4     600519.SH   20231225  1671.00  1678.60  1668.00  1672.00
3     600519.SH   20231226  1672.50  1674.90  1657.50  1670.00
2     600519.SH   20231227  1668.00  1677.15  1661.00  1667.06
1     600519.SH   20231228  1670.99  1727.99  1667.06  1724.99
0     600519.SH   20231229  1720.00  1749.58  1720.00  1726.00

[5349 rows x 6 columns]

In [171]:
df.to_csv('./maotai.csv')

In [172]:
df=pd.read_csv('./maotai.csv')

In [173]:
df.head()

   Unnamed: 0    ts_code  trade_date   open   high    low  close
0        5348  600519.SH    20010827  34.51  37.78  32.85  35.55
1        5347  600519.SH    20010828  34.99  37.00  34.61  36.86
2        5346  600519.SH    20010829  36.98  37.00  36.10  36.38
3        5345  600519.SH    20010830  36.28  37.51  36.00  37.10
4        5344  600519.SH    20010831  37.15  37.62  36.80  37.01

In [174]:
df.drop(labels='Unnamed: 0',axis=1,inplace=True)

In [175]:
df

        ts_code  trade_date     open     high      low    close
0     600519.SH    20010827    34.51    37.78    32.85    35.55
1     600519.SH    20010828    34.99    37.00    34.61    36.86
2     600519.SH    20010829    36.98    37.00    36.10    36.38
3     600519.SH    20010830    36.28    37.51    36.00    37.10
4     600519.SH    20010831    37.15    37.62    36.80    37.01
...         ...         ...      ...      ...      ...      ...
5344  600519.SH    20231225  1671.00  1678.60  1668.00  1672.00
5345  600519.SH    20231226  1672.50  1674.90  1657.50  1670.00
5346  600519.SH    20231227  1668.00  1677.15  1661.00  1667.06
5347  600519.SH    20231228  1670.99  1727.99  1667.06  1724.99
5348  600519.SH    20231229  1720.00  1749.58  1720.00  1726.00

[5349 rows x 6 columns]

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5349 entries, 0 to 5348
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ts_code     5349 non-null   object
 1   trade_date  5349 non-null   int64
 2   open        5349 non-null   float64
 3   high        5349 non-null   float64
 4   low         5349 non-null   float64
 5   close       5349 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 250.9+ KB

In [177]:
#将trade_date转化为时间
df['trade_date'] = pd.to_datetime(df['trade_date'],format='%Y%m%d')
print(df)

        ts_code trade_date     open     high      low    close
0     600519.SH 2001-08-27    34.51    37.78    32.85    35.55
1     600519.SH 2001-08-28    34.99    37.00    34.61    36.86
2     600519.SH 2001-08-29    36.98    37.00    36.10    36.38
3     600519.SH 2001-08-30    36.28    37.51    36.00    37.10
4     600519.SH 2001-08-31    37.15    37.62    36.80    37.01
...         ...        ...      ...      ...      ...      ...
5344  600519.SH 2023-12-25  1671.00  1678.60  1668.00  1672.00
5345  600519.SH 2023-12-26  1672.50  1674.90  1657.50  1670.00
5346  600519.SH 2023-12-27  1668.00  1677.15  1661.00  1667.06
5347  600519.SH 2023-12-28  1670.99  1727.99  1667.06  1724.99
5348  600519.SH 2023-12-29  1720.00  1749.58  1720.00  1726.00

[5349 rows x 6 columns]

In [178]:
df = df.rename(columns={'trade_date':'date'})

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5349 entries, 0 to 5348
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ts_code  5349 non-null   object
 1   date     5349 non-null   datetime64[ns]
 2   open     5349 non-null   float64
 3   high     5349 non-null   float64
 4   low      5349 non-null   float64
 5   close    5349 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 250.9+ KB

In [180]:
#将date作为行索引
df.set_index('date',inplace=True)

In [181]:
df

              ts_code     open     high      low    close
date
2001-08-27  600519.SH    34.51    37.78    32.85    35.55
2001-08-28  600519.SH    34.99    37.00    34.61    36.86
2001-08-29  600519.SH    36.98    37.00    36.10    36.38
2001-08-30  600519.SH    36.28    37.51    36.00    37.10
2001-08-31  600519.SH    37.15    37.62    36.80    37.01
...               ...      ...      ...      ...      ...
2023-12-25  600519.SH  1671.00  1678.60  1668.00  1672.00
2023-12-26  600519.SH  1672.50  1674.90  1657.50  1670.00
2023-12-27  600519.SH  1668.00  1677.15  1661.00  1667.06
2023-12-28  600519.SH  1670.99  1727.99  1667.06  1724.99
2023-12-29  600519.SH  1720.00  1749.58  1720.00  1726.00

[5349 rows x 5 columns]

# `捕获股票涨幅的日期

In [182]:
#输出该股票所有收盘比开盘上涨3%的日期
((df['close']-df['open'])/df['open']) >0.03
df.loc[((df['close']-df['open'])/df['open']) >0.03].index#获取true对应的行数据

DatetimeIndex(['2001-08-27', '2001-08-28', '2001-09-10', '2001-12-21',
               '2002-01-18', '2002-01-31', '2003-01-14', '2003-10-29',
               '2004-01-05', '2004-01-14',
               ...
               '2022-06-10', '2022-06-17', '2022-08-31', '2022-11-01',
               '2022-11-04', '2022-11-15', '2023-01-05', '2023-05-22',
               '2023-07-28', '2023-12-28'],
              dtype='datetime64[ns]', name='date', length=352, freq=None)

# `捕获股票下跌的日期

In [183]:
#输出跌幅超过2%的日期
df.loc[(df['open']- df['close'].shift(1))/df['close'].shift(1) < -0.02].index

DatetimeIndex(['2001-09-12', '2002-06-26', '2002-07-25', '2002-12-13',
               '2003-07-14', '2004-07-01', '2004-10-29', '2005-08-05',
               '2006-05-25', '2006-08-21',
               ...
               '2021-04-28', '2021-08-20', '2021-11-01', '2022-03-14',
               '2022-03-15', '2022-03-28', '2022-10-13', '2022-10-24',
               '2022-11-28', '2023-02-06'],
              dtype='datetime64[ns]', name='date', length=105, freq=None)

# 股票买卖收益分析

In [188]:
#策略:每个月的第一个交易日买入一手，买一年最后一起卖出
df

              ts_code     open     high      low    close
date
2001-08-27  600519.SH    34.51    37.78    32.85    35.55
2001-08-28  600519.SH    34.99    37.00    34.61    36.86
2001-08-29  600519.SH    36.98    37.00    36.10    36.38
2001-08-30  600519.SH    36.28    37.51    36.00    37.10
2001-08-31  600519.SH    37.15    37.62    36.80    37.01
...               ...      ...      ...      ...      ...
2023-12-25  600519.SH  1671.00  1678.60  1668.00  1672.00
2023-12-26  600519.SH  1672.50  1674.90  1657.50  1670.00
2023-12-27  600519.SH  1668.00  1677.15  1661.00  1667.06
2023-12-28  600519.SH  1670.99  1727.99  1667.06  1724.99
2023-12-29  600519.SH  1720.00  1749.58  1720.00  1726.00

[5349 rows x 5 columns]

In [189]:
new_df = df['2010-01':'2020-02']
new_df

              ts_code     open     high      low    close
date
2010-01-04  600519.SH   172.00   172.00   169.31   169.94
2010-01-05  600519.SH   170.99   171.50   169.00   169.44
2010-01-06  600519.SH   168.99   169.50   166.31   166.76
2010-01-07  600519.SH   166.76   167.19   161.88   163.72
2010-01-08  600519.SH   164.00   164.00   160.10   162.00
...               ...      ...      ...      ...      ...
2020-02-24  600519.SH  1105.50  1110.00  1085.50  1087.18
2020-02-25  600519.SH  1078.00  1082.09  1067.88  1074.81
2020-02-26  600519.SH  1062.00  1084.00  1055.00  1073.70
2020-02-27  600519.SH  1076.00  1094.99  1076.00  1087.39
2020-02-28  600519.SH  1070.30  1082.00  1049.97  1057.00

[2461 rows x 5 columns]

In [192]:
#买股票
df_monthly = new_df.resample('M').first()#根据月份从原始数据中提取指定的数据
df_monthly

C:\Users\86157\AppData\Local\Temp\ipykernel_18004\3660992148.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_monthly = new_df.resample('M').first()#根据月份从原始数据中提取指定的数据

              ts_code     open     high      low    close
date
2010-01-31  600519.SH   172.00   172.00   169.31   169.94
2010-02-28  600519.SH   168.88   169.58   167.01   168.89
2010-03-31  600519.SH   166.45   167.45   165.99   166.24
2010-04-30  600519.SH   158.78   160.50   158.76   160.06
2010-05-31  600519.SH   127.99   129.56   126.89   128.64
...               ...      ...      ...      ...      ...
2019-10-31  600519.SH  1153.00  1180.00  1152.01  1167.10
2019-11-30  600519.SH  1181.00  1191.95  1172.50  1185.00
2019-12-31  600519.SH  1118.20  1140.02  1118.20  1133.00
2020-01-31  600519.SH  1128.00  1145.06  1116.00  1130.00
2020-02-29  600519.SH   985.00  1010.68   980.00  1003.92

[122 rows x 5 columns]

In [194]:
#买入股票的花费
cos =df_monthly['open'].sum()*100
cos

4373739.0

In [199]:
#卖出股票的钱
#切除最后一年
df_yearly = new_df.resample('A').last()[:-1]
resv = df_yearly['open'].sum()*1200
resv

C:\Users\86157\AppData\Local\Temp\ipykernel_18004\698713969.py:3: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  df_yearly = new_df.resample('A').last()[:-1]

4687848.0

In [200]:
#估计手中剩余的股票计为收益
#使用昨日收盘价作为单价
last_monry = 200 * new_df['close'][-1]
last_monry

C:\Users\86157\AppData\Local\Temp\ipykernel_18004\3361897020.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  last_monry = 200 * new_df['close'][-1]

211400.0

In [201]:
#计算总收益
resv+last_monry-cos

525509.0